
import React, { useState, useMemo, useEffect, useRef, useContext } from 'react';
import type { QuizData, Question, QuizFormData } from '../types.ts';
import { generateVisualExplanation } from '../services/geminiService.ts';
import html2pdf from 'html2pdf.js';
import { AppContext } from '../context/AppContext.tsx';
import VideoSummaryModal from './VideoSummaryModal.tsx';
import ArtGeneratorModal from './ArtGeneratorModal.tsx';

interface QuizDisplayProps {
    quizData: QuizData;
    formData: QuizFormData;
}

// Helper to format seconds into MM:SS
const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
};

interface VisualExplanationModalProps {
    question: Question;
    onClose: () => void;
    cachedImage?: string;
    onImageGenerated: (questionId: number, url: string) => void;
}

const VisualExplanationModal: React.FC<VisualExplanationModalProps> = ({ question, onClose, cachedImage, onImageGenerated }) => {
    const [imageUrl, setImageUrl] = useState<string | null>(cachedImage || null);
    const [isLoading, setIsLoading] = useState(!cachedImage);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (cachedImage) return;

        let isMounted = true;
        const generateImage = async () => {
            setIsLoading(true);
            setError(null);
            try {
                const result = await generateVisualExplanation(question);
                if (isMounted) {
                    setImageUrl(result);
                    onImageGenerated(question.id, result);
                }
            } catch (err: any) {
                if (isMounted) {
                    setError(err.message || 'Failed to generate image.');
                }
            } finally {
                if (isMounted) {
                    setIsLoading(false);
                }
            }
        };

        generateImage();

        return () => {
            isMounted = false;
        };
    }, [question, cachedImage, onImageGenerated]);

    return (
        <div className="fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4 animate-fade-in" onClick={onClose}>
            <div className="bg-[var(--surface-color)] w-full max-w-2xl rounded-xl shadow-2xl border border-[var(--border-color)] flex flex-col max-h-[90vh]" onClick={e => e.stopPropagation()}>
                <header className="flex items-center justify-between p-4 border-b border-[var(--border-color)]">
                    <h3 className="font-display text-lg font-bold">Visual Explanation</h3>
                    <button onClick={onClose} className="w-8 h-8 rounded-full hover:bg-white/10 transition-colors">&times;</button>
                </header>
                <div className="p-6 flex-1 overflow-y-auto">
                    <p className="font-semibold text-md mb-4 text-[var(--text-muted-color)]">{question.question}</p>
                    <div className="w-full aspect-video bg-black/20 rounded-lg flex items-center justify-center border border-[var(--border-color)] overflow-hidden relative">
                        {isLoading && (
                             <div className="text-center">
                                <svg className="animate-spin h-8 w-8 text-[var(--primary-color)] mx-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                <p className="mt-2 text-sm text-[var(--text-muted-color)]">Sketching the answer...</p>
                            </div>
                        )}
                        {error && <p className="text-red-400 px-4 text-center">{error}</p>}
                        {imageUrl && <img src={imageUrl} alt="Visual explanation of the answer" className="w-full h-full object-contain" />}
                    </div>
                    <p className="mt-4 text-sm text-[var(--text-muted-color)] italic">
                        This visual explanation was generated by AI to help illustrate the concept.
                    </p>
                </div>
            </div>
        </div>
    );
};

interface InteractiveQuestionCardProps {
    question: Question;
    index: number;
    userAnswer: string;
    isSubmitted: boolean;
    hasVisual: boolean;
    isMarked: boolean;
    onAnswerChange: (val: string) => void;
    onVisualize: (q: Question) => void;
    onToggleMark: () => void;
}

const InteractiveQuestionCard: React.FC<InteractiveQuestionCardProps> = ({ 
    question, index, userAnswer, isSubmitted, hasVisual, isMarked, onAnswerChange, onVisualize, onToggleMark
}) => {
    const isCorrect = isSubmitted && (
        question.type === 'matching' || question.type === 'ordering' 
        ? true // Hard to auto-grade complex types strictly, treat as review
        : userAnswer.toLowerCase().trim() === question.answer.toLowerCase().trim()
    );
    
    const cardBorderClass = isSubmitted
        ? (isCorrect ? 'border-green-500/50' : 'border-red-500/50')
        : 'border-[var(--border-color)]';

    // Memoize shuffled responses for matching questions
    const shuffledResponses = useMemo(() => {
        if (question.type === 'matching' && question.responses) {
            return [...question.responses].sort(() => Math.random() - 0.5);
        }
        return [];
    }, [question.type, question.responses]);

    return (
        <div className={`bg-[var(--bg-color)] p-6 rounded-lg border-2 mb-6 transition-all duration-300 ${cardBorderClass}`}>
            <div className="flex justify-between items-start gap-4">
                 <div className="flex items-start gap-3 flex-grow">
                    <button 
                        onClick={onToggleMark}
                        className={`mt-1 transition-colors ${isMarked ? 'text-yellow-400' : 'text-[var(--text-muted-color)] hover:text-[var(--text-color)]'}`}
                        title={isMarked ? "Unmark question" : "Mark as difficult for review"}
                    >
                        <i className={`fas fa-flag text-lg`}></i>
                    </button>
                    <p className="font-semibold text-lg mb-4">
                        {index + 1}. {question.question}
                    </p>
                </div>
                {isSubmitted && (
                    <span className={`px-3 py-1 text-xs font-bold rounded-full ${isCorrect ? 'bg-green-500/20 text-green-400' : 'bg-red-500/20 text-red-400'}`}>
                        {question.type === 'matching' || question.type === 'ordering' ? 'Review' : (isCorrect ? 'Correct' : 'Incorrect')}
                    </span>
                )}
            </div>

            {/* Interactive Inputs */}
            <div className="mb-4 pl-8">
                {question.type === 'multiple-choice' && question.options && (
                    <div className="space-y-2">
                        {question.options.map((opt, i) => {
                            const isSelected = userAnswer === opt;
                            const isRealAnswer = isSubmitted && opt === question.answer;
                            let optionClass = "p-3 rounded-md border border-transparent transition-colors cursor-pointer flex items-center gap-3";
                            
                            if (isSubmitted) {
                                if (isRealAnswer) optionClass += " bg-green-500/20 border-green-500/50";
                                else if (isSelected && !isRealAnswer) optionClass += " bg-red-500/20 border-red-500/50 opacity-75";
                                else optionClass += " opacity-50";
                            } else {
                                optionClass += isSelected ? " bg-[var(--primary-color)]/20 border-[var(--primary-color)]" : " hover:bg-white/5 border-[var(--border-color)]";
                            }

                            return (
                                <label key={i} className={optionClass}>
                                    <input 
                                        type="radio" 
                                        name={`question-${question.id}`} 
                                        value={opt} 
                                        checked={isSelected} 
                                        onChange={(e) => onAnswerChange(e.target.value)}
                                        disabled={isSubmitted}
                                        className="sr-only"
                                    />
                                    <div className={`w-4 h-4 rounded-full border flex items-center justify-center ${isSelected ? 'border-[var(--primary-color)]' : 'border-gray-500'}`}>
                                        {isSelected && <div className="w-2 h-2 rounded-full bg-[var(--primary-color)]"></div>}
                                    </div>
                                    <span>{opt}</span>
                                </label>
                            );
                        })}
                    </div>
                )}

                {question.type === 'true-false' && (
                    <div className="flex gap-4">
                        {['True', 'False'].map((opt) => {
                            const isSelected = userAnswer.toLowerCase() === opt.toLowerCase();
                             return (
                                <label key={opt} className={`flex-1 p-3 rounded-md border text-center cursor-pointer transition-all ${
                                    isSelected 
                                    ? 'bg-[var(--primary-color)]/20 border-[var(--primary-color)] font-bold' 
                                    : 'border-[var(--border-color)] hover:bg-white/5'
                                } ${isSubmitted ? 'opacity-60 cursor-default' : ''}`}>
                                    <input 
                                        type="radio" 
                                        name={`question-${question.id}`} 
                                        value={opt} 
                                        checked={isSelected} 
                                        onChange={(e) => onAnswerChange(e.target.value)}
                                        disabled={isSubmitted}
                                        className="sr-only"
                                    />
                                    {opt}
                                </label>
                            );
                        })}
                    </div>
                )}

                {question.type === 'fill-blank' && (
                    <input 
                        type="text" 
                        value={userAnswer} 
                        onChange={(e) => onAnswerChange(e.target.value)} 
                        disabled={isSubmitted}
                        placeholder="Type your answer here..."
                        className="w-full p-3 bg-black/20 border border-[var(--border-color)] rounded-md focus:ring-2 focus:ring-[var(--primary-color)] focus:outline-none disabled:opacity-60"
                    />
                )}

                {(question.type === 'matching' || question.type === 'ordering') && (
                    <div className="text-sm text-[var(--text-muted-color)] p-4 bg-black/20 rounded-lg border border-[var(--border-color)]">
                        {question.type === 'matching' && question.stems && question.responses && (
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-4">
                                <ul className="space-y-2">
                                    {question.stems.map((stem, i) => <li key={i}><span className="font-bold mr-2">{i + 1}.</span>{stem}</li>)}
                                </ul>
                                <ul className="space-y-2">
                                    {shuffledResponses.map((res, i) => <li key={i}><span className="font-bold mr-2">{String.fromCharCode(65 + i)}.</span>{res}</li>)}
                                </ul>
                            </div>
                        )}
                        {question.type === 'ordering' && question.items && (
                            <ul className="list-disc list-inside space-y-1">
                                {question.items.map((item, i) => <li key={i}>{item}</li>)}
                            </ul>
                        )}
                        {!isSubmitted && <p className="mt-4 italic text-xs opacity-70 text-center">Mentally solve this, then check the answer key upon submission.</p>}
                    </div>
                )}
            </div>

            {/* Explanation Section - Revealed on Submit */}
            {isSubmitted && (
                <div className="mt-4 pt-4 border-t border-[var(--border-color)] animate-fade-in pl-8">
                    <div className="flex justify-between items-start mb-2">
                        <span className="text-xs font-bold uppercase tracking-wider text-[var(--text-muted-color)]">Correct Answer</span>
                        <button
                            onClick={() => onVisualize(question)}
                            className={`flex items-center gap-2 text-xs px-3 py-1.5 rounded-md transition-colors ${
                                hasVisual 
                                ? 'bg-green-500/10 text-green-400 hover:bg-green-500/20' 
                                : 'bg-blue-500/10 text-blue-300 hover:bg-blue-500/20'
                            }`}
                            title={hasVisual ? "View existing visual explanation" : "Generate visual explanation"}
                        >
                            <i className={`fas ${hasVisual ? 'fa-image' : 'fa-pencil-ruler'}`}></i>
                            {hasVisual ? 'View Diagram' : 'Visualize Answer'}
                        </button>
                    </div>
                    <p className="text-green-400 font-bold mb-2">{question.answer}</p>
                    
                    <span className="text-xs font-bold uppercase tracking-wider text-[var(--text-muted-color)] block mb-1">Explanation</span>
                    <p className="text-sm leading-relaxed">{question.explanation}</p>
                </div>
            )}
        </div>
    );
};


const QuizDisplay: React.FC<QuizDisplayProps> = ({ quizData, formData }) => {
    const { resetQuiz, addBookmark } = useContext(AppContext);
    
    // State
    const [userAnswers, setUserAnswers] = useState<Record<number, string>>({});
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [elapsedTime, setElapsedTime] = useState(0);
    const [isTimerRunning, setIsTimerRunning] = useState(true);
    const [visualExplanations, setVisualExplanations] = useState<Record<number, string>>({});
    const [markedQuestionIds, setMarkedQuestionIds] = useState<Set<number>>(new Set());
    const [showMarkedOnly, setShowMarkedOnly] = useState(false);
    
    // UI State
    const [isDownloading, setIsDownloading] = useState(false);
    const [visualizingQuestion, setVisualizingQuestion] = useState<Question | null>(null);
    const [showVideoModal, setShowVideoModal] = useState(false);
    const [showArtModal, setShowArtModal] = useState(false);
    const quizPaperRef = useRef<HTMLDivElement>(null);

    // Timer Logic
    useEffect(() => {
        let interval: number | undefined;
        if (isTimerRunning && !isSubmitted) {
            interval = window.setInterval(() => {
                setElapsedTime(prev => prev + 1);
            }, 1000);
        }
        return () => clearInterval(interval);
    }, [isTimerRunning, isSubmitted]);

    const handleAnswerChange = (questionId: number, value: string) => {
        setUserAnswers(prev => ({ ...prev, [questionId]: value }));
    };

    const handleSubmit = () => {
        setIsSubmitted(true);
        setIsTimerRunning(false);
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };

    const handleImageGenerated = (questionId: number, imageUrl: string) => {
        setVisualExplanations(prev => ({ ...prev, [questionId]: imageUrl }));
    };

    const toggleQuestionMark = (id: number) => {
        setMarkedQuestionIds(prev => {
            const newSet = new Set(prev);
            if (newSet.has(id)) {
                newSet.delete(id);
            } else {
                newSet.add(id);
            }
            return newSet;
        });
    };

    // Calculate Score
    const scoreData = useMemo(() => {
        if (!isSubmitted) return null;
        let correctCount = 0;
        let scorableQuestions = 0;

        quizData.questions.forEach(q => {
            // Only score auto-gradable types
            if (q.type === 'multiple-choice' || q.type === 'true-false' || q.type === 'fill-blank') {
                scorableQuestions++;
                const userAns = userAnswers[q.id] || "";
                if (userAns.toLowerCase().trim() === q.answer.toLowerCase().trim()) {
                    correctCount++;
                }
            }
        });

        const percentage = scorableQuestions > 0 ? Math.round((correctCount / scorableQuestions) * 100) : 0;
        return { correctCount, scorableQuestions, percentage };
    }, [isSubmitted, quizData.questions, userAnswers]);

    // Filter questions based on review mode
    const displayedQuestions = showMarkedOnly 
        ? quizData.questions.filter(q => markedQuestionIds.has(q.id))
        : quizData.questions;

    const handleDownloadPDF = async () => {
        if (!quizPaperRef.current) return;
        setIsDownloading(true);

        // Wait for state updates if needed (mostly for ensuring styles are applied)
        await new Promise(resolve => setTimeout(resolve, 100));

        const element = quizPaperRef.current;
        const opt = {
            margin: 0.5,
            filename: `${quizData.title.replace(/\s+/g, '_')}_Quiz.pdf`,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2, useCORS: true },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
        };
        
        await html2pdf().set(opt).from(element).save();
        setIsDownloading(false);
    };

    const printQuiz = () => {
        window.print();
    };

    return (
        <div className="w-full max-w-4xl mx-auto">
            {/* Sticky Header Actions */}
            <div className="quiz-actions-header sticky top-24 z-40 flex flex-col md:flex-row justify-between items-center gap-4 mb-6 p-3 bg-[var(--surface-color)]/90 backdrop-blur-md rounded-lg border border-[var(--border-color)] shadow-lg">
                <div className="flex items-center gap-3 w-full md:w-auto justify-between md:justify-start">
                    <button onClick={resetQuiz} className="flex items-center gap-2 px-4 py-2 rounded-md bg-gray-500/20 hover:bg-gray-500/40 transition-colors text-sm">
                        <i className="fas fa-arrow-left"></i> Back
                    </button>
                    
                    {/* Timer Badge */}
                    <div className={`flex items-center gap-2 px-4 py-2 rounded-md border ${isSubmitted ? 'bg-black/20 border-[var(--border-color)]' : 'bg-[var(--surface-color)] border-[var(--primary-color)] text-[var(--primary-color)]'} font-mono font-bold text-lg`}>
                        <i className={`fas fa-clock ${!isSubmitted && 'animate-pulse'}`}></i>
                        <span>{formatTime(elapsedTime)}</span>
                    </div>
                </div>

                <div className="flex items-center gap-2 flex-wrap justify-end">
                    {markedQuestionIds.size > 0 && (
                        <button 
                            onClick={() => setShowMarkedOnly(!showMarkedOnly)}
                            className={`flex items-center gap-2 px-3 py-2 rounded-md text-sm transition-colors ${showMarkedOnly ? 'bg-yellow-500 text-white' : 'bg-yellow-500/20 text-yellow-400 hover:bg-yellow-500/40'}`}
                            title={showMarkedOnly ? "Show all questions" : "Filter to see only marked questions"}
                        >
                            <i className={`fas ${showMarkedOnly ? 'fa-list-ol' : 'fa-flag'}`}></i>
                            {showMarkedOnly ? 'Show All' : `Review (${markedQuestionIds.size})`}
                        </button>
                    )}

                     <button 
                        onClick={() => addBookmark(quizData.title, formData)}
                        className="flex items-center justify-center w-10 h-10 rounded-md bg-yellow-500/20 hover:bg-yellow-500/40 transition-colors text-yellow-400"
                        title="Bookmark Quiz"
                    >
                        <i className="fas fa-bookmark"></i>
                    </button>

                    <button onClick={() => setShowArtModal(true)} className="flex items-center justify-center w-10 h-10 rounded-md bg-pink-500/20 hover:bg-pink-500/40 transition-colors text-pink-400" title="Generate AI Art">
                        <i className="fas fa-palette"></i>
                    </button>

                    <button onClick={() => setShowVideoModal(true)} className="flex items-center justify-center w-10 h-10 rounded-md bg-teal-500/20 hover:bg-teal-500/40 transition-colors text-teal-400" title="Generate Video Summary">
                        <i className="fas fa-video"></i>
                    </button>
                    
                    <button onClick={printQuiz} className="flex items-center justify-center w-10 h-10 rounded-md bg-blue-500/20 hover:bg-blue-500/40 transition-colors text-blue-400" title="Print Quiz">
                         <i className="fas fa-print"></i>
                    </button>

                    <button 
                        onClick={handleDownloadPDF} 
                        disabled={isDownloading}
                        className="flex items-center gap-2 px-3 py-2 rounded-md bg-purple-500/20 hover:bg-purple-500/40 transition-colors text-purple-400 disabled:opacity-50 text-sm font-semibold"
                        title="Download Quiz as PDF"
                    >
                        {isDownloading ? <i className="fas fa-spinner animate-spin"></i> : <i className="fas fa-file-pdf"></i>}
                        <span>Download PDF</span>
                    </button>

                    {!isSubmitted && (
                        <button 
                            onClick={handleSubmit}
                            className="flex items-center gap-2 px-6 py-2 rounded-md bg-gradient-to-r from-green-500 to-emerald-600 text-white font-bold shadow-lg hover:shadow-green-500/20 hover:scale-105 transition-all"
                        >
                            <i className="fas fa-check-circle"></i> Finish Quiz
                        </button>
                    )}
                </div>
            </div>

            <div ref={quizPaperRef} className="quiz-paper p-6 md:p-12 bg-[var(--surface-color)] rounded-xl shadow-2xl shadow-black/30 border border-[var(--border-color)]">
                <header className="text-center border-b-2 border-[var(--border-color)] pb-6 mb-8">
                    <h1 className="text-3xl md:text-4xl font-bold font-display text-transparent bg-clip-text bg-gradient-to-r from-[var(--primary-color)] to-[var(--secondary-color)]">{quizData.title}</h1>
                    <div className="flex justify-center gap-6 mt-4 text-sm text-[var(--text-muted-color)]">
                        <span className="capitalize"><i className="fas fa-layer-group mr-2"></i>{quizData.difficulty}</span>
                        <span><i className="fas fa-list-ol mr-2"></i>{quizData.numQuestions} Questions</span>
                        <span><i className="fas fa-tag mr-2"></i>{quizData.topic}</span>
                    </div>
                </header>

                {/* Results Card */}
                {isSubmitted && scoreData && (
                    <div className="mb-8 p-6 rounded-lg bg-gradient-to-br from-[var(--surface-dark)] to-black/40 border border-[var(--border-color)] animate-fade-in">
                        <h2 className="text-2xl font-bold font-display mb-4 text-center">Assessment Complete</h2>
                        <div className="grid grid-cols-3 gap-4 text-center">
                            <div className="p-4 rounded-lg bg-white/5">
                                <p className="text-sm text-[var(--text-muted-color)] mb-1">Score</p>
                                <p className={`text-3xl font-bold ${scoreData.percentage >= 70 ? 'text-green-400' : 'text-orange-400'}`}>
                                    {scoreData.percentage}%
                                </p>
                            </div>
                            <div className="p-4 rounded-lg bg-white/5">
                                <p className="text-sm text-[var(--text-muted-color)] mb-1">Correct</p>
                                <p className="text-3xl font-bold text-[var(--text-color)]">
                                    {scoreData.correctCount} <span className="text-lg text-[var(--text-muted-color)]">/ {scoreData.scorableQuestions}</span>
                                </p>
                            </div>
                            <div className="p-4 rounded-lg bg-white/5">
                                <p className="text-sm text-[var(--text-muted-color)] mb-1">Time</p>
                                <p className="text-3xl font-bold text-[var(--primary-color)]">{formatTime(elapsedTime)}</p>
                            </div>
                        </div>
                         {quizData.questions.some(q => q.type === 'matching' || q.type === 'ordering') && (
                             <p className="text-center text-xs text-[var(--text-muted-color)] mt-4 italic">
                                 * Score excludes matching/ordering questions which require self-review.
                             </p>
                         )}
                    </div>
                )}
                
                <section>
                    {displayedQuestions.length > 0 ? (
                        displayedQuestions.map((q) => {
                            // Determine original index to preserve question numbering
                            const originalIndex = quizData.questions.findIndex(orig => orig.id === q.id);
                            return (
                                <InteractiveQuestionCard 
                                    key={q.id} 
                                    question={q} 
                                    index={originalIndex} 
                                    userAnswer={userAnswers[q.id] || ''}
                                    isSubmitted={isSubmitted}
                                    hasVisual={!!visualExplanations[q.id]}
                                    isMarked={markedQuestionIds.has(q.id)}
                                    onAnswerChange={(val) => handleAnswerChange(q.id, val)}
                                    onVisualize={setVisualizingQuestion}
                                    onToggleMark={() => toggleQuestionMark(q.id)}
                                />
                            );
                        })
                    ) : (
                        <div className="text-center py-12 text-[var(--text-muted-color)] border-2 border-dashed border-[var(--border-color)] rounded-lg">
                            <i className="fas fa-filter text-3xl mb-3 opacity-50"></i>
                            <p>No marked questions found.</p>
                            <button 
                                onClick={() => setShowMarkedOnly(false)} 
                                className="text-[var(--primary-color)] hover:underline mt-2 text-sm"
                            >
                                Show all questions
                            </button>
                        </div>
                    )}
                </section>
            </div>
            
            {visualizingQuestion && (
                <VisualExplanationModal 
                    question={visualizingQuestion} 
                    cachedImage={visualExplanations[visualizingQuestion.id]}
                    onImageGenerated={handleImageGenerated}
                    onClose={() => setVisualizingQuestion(null)} 
                />
            )}
            {showVideoModal && <VideoSummaryModal topic={quizData.topic} onClose={() => setShowVideoModal(false)} />}
            {showArtModal && <ArtGeneratorModal topic={quizData.topic} onClose={() => setShowArtModal(false)} />}
        </div>
    );
};

export default QuizDisplay;
